version: '{build}'
skip_tags: true
clone_depth: 10
environment:
  matrix:
    - appveyor_build_worker_image: Visual Studio 2022
      JAVA_HOME: C:\Program Files\Java\jdk17
branches:
  only:
    - master
    - dev/v20
    - legacy/v16
  except:
    - gh-pages
init:
  - cmd: SET PATH=%JAVA_HOME%\bin;%PATH%
install:
  - cmd: SET MAVEN_OPTS=-Xmx4g
  - cmd: SET JAVA_OPTS=-Xmx4g
  - cmd: mvn --version
  - cmd: java -version
build_script:
  - mvn clean package -DskipTests --batch-mode
test_script:
  - mvn surefire:test --batch-mode
cache:
  - C:\Users\appveyor\.m2
artifacts:
- path: target/GriefPrevention.jar
  name: GriefPrevention
