commit-hash: ${git.commit.id.describe-short}
git-repo: LemonGamingLtd/GriefPrevention
name: GriefPrevention
main: me.ryanhamshire.GriefPrevention.GriefPrevention
softdepend:
  - Vault
  - Multiverse-Core
  - My_Worlds
  - MystCraft
  - Transporter
  - TheUnderground
  - WorldGuard
  - WorldEdit
  - RoyalCommands
  - MultiWorld
  - Denizen
dev-url: https://dev.bukkit.org/projects/grief-prevention
loadbefore:
  - TheUnderground
version: ${git.commit.id.describe}
api-version: '1.17'
commands:
  abandonclaim:
    description: Deletes a claim.
    usage: /AbandonClaim
    aliases:
      - unclaim
      - declaim
      - removeclaim
      - disclaim
    permission: griefprevention.claims
  abandontoplevelclaim:
    description: Deletes a claim and all its subdivisions.
    usage: /AbandonTopLevelClaim
    permission: griefprevention.claims
  abandonallclaims:
    description: Deletes ALL your claims.
    usage: /AbandonAllClaims
    permission: griefprevention.claims
  trust:
    description: Grants a player full access to your claim(s).
    usage: /Trust <player>  Grants a player permission to build.  See also /UnTrust,
      /ContainerTrust, /AccessTrust, and /PermissionTrust.
    aliases: tr
    permission: griefprevention.claims
  untrust:
    description: Revokes a player's access to your claim(s).
    usage: /UnTrust <player>
    aliases: ut
    permission: griefprevention.claims
  containertrust:
    description: Grants a player access to your claim's containers, crops, animals,
      bed, buttons, and levers.
    usage: /ContainerTrust <player>.  Grants a player access to your inventory, crops,
      animals, bed, and buttons/levers.
    aliases: ct
    permission: griefprevention.claims
  accesstrust:
    description: Grants a player entry to your claim(s) and use of your bed, buttons,
      and levers.
    usage: /AccessTrust <player>.  Grants a player access to your bed, buttons, and
      levers.
    aliases: at
    permission: griefprevention.claims
  permissiontrust:
    description: Grants a player permission to grant his level of permission to others.
    usage: /PermissionTrust <player>.  Permits a player to share his permission level
      with others.
    aliases: pt
    permission: griefprevention.claims
  subdivideclaims:
    description: Switches the shovel tool to subdivision mode, used to subdivide your
      claims.
    usage: /SubdivideClaims
    aliases:
      - sc
      - subdivideclaim
    permission: griefprevention.claims
  restrictsubclaim:
    description: Restricts a subclaim, so that it inherits no permissions from the
      parent claim
    usage: /restrictsubclaim
    aliases: rsc
    permission: griefprevention.claims
  adjustbonusclaimblocks:
    description: Adds or subtracts bonus claim blocks for a player.
    usage: /AdjustBonusClaimBlocks <player> <amount>
    permission: griefprevention.adjustclaimblocks
    aliases: acb
  adjustbonusclaimblocksall:
    description: Adds or subtracts bonus claim blocks for all online players.
    usage: /AdjustBonusClaimBlocksAll <amount>
    permission: griefprevention.adjustclaimblocks
    aliases: acball
  setaccruedclaimblocks:
    description: Updates a player's accrued claim block total.
    usage: /SetAccruedClaimBlocks <player> <amount>
    permission: griefprevention.adjustclaimblocks
    aliases: scb
  deleteclaim:
    description: Deletes the claim you're standing in, even if it's not your claim.
    usage: /DeleteClaim
    permission: griefprevention.deleteclaims
  deleteallclaims:
    description: Deletes all of another player's claims.
    usage: /DeleteAllClaims <player>
    permission: griefprevention.deleteclaims
  deleteclaimsinworld:
    description: Deletes all the claims in a world.  Only usable at the server console.
    usage: /DeleteClaimsInWorld <world>
    aliases:
      - deleteallclaimsinworld
      - clearclaimsinworld
      - clearallclaimsinworld
    permission: griefprevention.deleteclaimsinworld
  deleteuserclaimsinworld:
    description: Deletes all the non-admin claims in a world.  Only usable at the
      server console.
    usage: /DeleteUserClaimsInWorld <world>
    aliases:
      - deletealluserclaimsinworld
      - clearuserclaimsinworld
      - clearalluserclaimsinworld
    permission: griefprevention.deleteclaimsinworld
  adminclaims:
    description: Switches the shovel tool to administrative claims mode.
    usage: /AdminClaims
    permission: griefprevention.adminclaims
    aliases: ac
  restorenature:
    description: Switches the shovel tool to restoration mode.
    usage: /RestoreNature
    permission: griefprevention.restorenature
    aliases: rn
  restorenatureaggressive:
    description: Switches the shovel tool to aggressive restoration mode.
    usage: /RestoreNatureAggressive
    permission: griefprevention.restorenatureaggressive
    aliases: rna
  restorenaturefill:
    description: Switches the shovel tool to fill mode.
    usage: /RestoreNatureFill <radius>
    permission: griefprevention.restorenatureaggressive
    aliases: rnf
  basicclaims:
    description: Switches the shovel tool back to basic claims mode.
    usage: /BasicClaims
    aliases: bc
    permission: griefprevention.claims
  extendclaim:
    description: Resizes the land claim you're standing in by pushing or pulling its
      boundary in the direction you're facing.
    usage: /ExtendClaim <numberOfBlocks>
    aliases:
      - expandclaim
      - resizeclaim
    permission: griefprevention.claims
  claim:
    description: Creates a land claim centered at your current location.
    usage: /Claim [optional radius]
    aliases:
      - createclaim
      - makeclaim
      - newclaim
    permission: griefprevention.claims
  buyclaimblocks:
    description: Purchases additional claim blocks with server money.  Doesn't work
      on servers without a Vault-compatible economy plugin.
    usage: /BuyClaimBlocks <numberOfBlocks>
    aliases: buyclaim
    permission: griefprevention.buysellclaimblocks
  sellclaimblocks:
    description: Sells your claim blocks for server money.  Doesn't work on servers
      without a Vault-compatible economy plugin.
    usage: /SellClaimBlocks <numberOfBlocks>
    aliases: sellclaim
    permission: griefprevention.buysellclaimblocks
  trapped:
    description: Ejects you to nearby unclaimed land.  Has a substantial cooldown
      period.
    usage: /Trapped
    permission: griefprevention.trapped
  trustlist:
    description: Lists permissions for the claim you're standing in.
    usage: /TrustList
    permission: griefprevention.claims
  siege:
    description: Initiates a siege versus another player.
    usage: /Siege <playerName>
    permission: griefprevention.siege
  ignoreclaims:
    description: Toggles ignore claims mode.
    usage: /IgnoreClaims
    permission: griefprevention.ignoreclaims
    aliases: ic
  deletealladminclaims:
    description: Deletes all administrative claims.
    usage: /DeleteAllAdminClaims
    permission: griefprevention.adminclaims
  adminclaimslist:
    description: Lists all administrative claims.
    usage: /AdminClaimsList
    permission: griefprevention.adminclaims
  transferclaim:
    description: Converts an administrative claim to a private claim.
    usage: /TransferClaim <player>
    aliases: giveclaim
    permission: griefprevention.transferclaim
  unlockdrops:
    description: Allows other players to pick up the items you dropped when you died.
    usage: /UnlockDrops
    permission: griefprevention.unlockdrops
  claimslist:
    description: Lists information about a player's claim blocks and claims.
    usage: /ClaimsList or /ClaimsList <player>
    aliases:
      - claimlist
      - listclaims
    permission: griefprevention.claims
  claimexplosions:
    description: Toggles whether explosives may be used in a specific land claim.
    usage: /ClaimExplosions
    permission: griefprevention.claims
    aliases: claimexplosion
  softmute:
    description: Toggles whether a player's messages will only reach other soft-muted
      players.
    usage: /SoftMute <player>
    permission: griefprevention.softmute
  gpreload:
    description: Reloads Grief Prevention's configuration settings.  Does NOT totally
      reload the entire plugin.
    usage: /gpreload
    permission: griefprevention.reload
  givepet:
    description: Allows a player to give away a pet he or she tamed.
    usage: /GivePet <player>
    permission: griefprevention.givepet
  gpblockinfo:
    description: Allows an administrator to get technical information about blocks
      in the world and items in hand.
    usage: /GPBlockInfo
    permission: griefprevention.gpblockinfo
  ignoreplayer:
    description: Ignores another player's chat messages.
    usage: /IgnorePlayer <player name>
    aliases:
      - ignore
    permission: griefprevention.ignore
  unignoreplayer:
    description: Unignores another player's chat messages.
    usage: /UnIgnorePlayer <player name>
    aliases:
      - unignore
    permission: griefprevention.ignore
  ignoredplayerlist:
    description: Lists the players you're ignoring in chat.
    usage: /IgnoredPlayerList
    aliases:
      - ignores
      - ignored
      - ignorelist
      - ignoredlist
      - listignores
      - listignored
      - ignoring
    permission: griefprevention.ignore
  separate:
    description: Forces two players to ignore each other in chat.
    usage: /Separate <player1> <player2>
    permission: griefprevention.separate
  unseparate:
    description: Reverses /separate.
    usage: /UnSeparate <player1> <player2>
    permission: griefprevention.separate
  claimbook:
    description: Gives a player a manual about claiming land.
    usage: /ClaimBook <player>
    permission: griefprevention.claimbook
permissions:
  griefprevention:
    createclaims:
      description: Grants permission to create claims.
      default: true
    admin:
      '*':
        description: Grants all administrative functionality.
        children:
          griefprevention:
            restorenature: true
            restorenatureaggressive: true
            ignoreclaims: true
            adminclaims: true
            adjustclaimblocks: true
            deleteclaims: true
            spam: true
            lava: true
            eavesdrop: true
            deathblow: true
            softmute: true
            reload: true
            visualizenearbyclaims: true
            overrideclaimcountlimit: true
            transferclaim: true
            claimslistother: true
            siegeimmune: true
            separate: true
            eavesdropsigns: true
            claimbook: true
            notignorable: true
            seeinactivity: true
            eavesdropimmune: true
            deleteclaimsinworld: true
            siegeteleport: true
            unlockothersdrops: true
            seeclaimsize: true
    siegeimmune:
      description: Makes a player immune to /Siege.
      default: op
    givepet:
      description: Grants permission to use /GivePet.
      default: true
    siege:
      description: Grants permission to use /Siege.
      default: true
    unlockdrops:
      description: Grants permission to use /UnlockDrops.
      default: true
    unlockothersdrops:
      description: Grants permission to use /UnlockDrops for other players.
      default: op
    trapped:
      description: Grants permission to use /Trapped.
      default: true
    claimslistother:
      description: Grants permission to use /ClaimsList to get another player's information.
      default: op
    restorenature:
      description: Grants permission to use /RestoreNature.
      default: op
    transferclaim:
      description: Grants permission to use /TransferClaim.
      default: op
    ignoreclaims:
      description: Grants permission to use /IgnoreClaims.
      default: op
    adminclaims:
      description: Grants permission to create administrative claims.
      default: op
    deleteclaims:
      description: Grants permission to delete other players' claims.
      default: op
    deleteclaimsinworld:
      description: Not used.  DeleteClaimsInWorld must be executed at the server console.
      default: op
    adjustclaimblocks:
      description: Grants permission to add or remove bonus blocks from a player's
        account.
      default: op
    spam:
      description: Grants permission to log in, send messages, and send commands rapidly.
      default: op
    lava:
      description: Grants permission to place lava near the surface and outside of
        claims.
      default: op
    eavesdrop:
      description: Allows a player to see whispered chat messages (/tell) and softmuted
        messages.
      default: op
    eavesdropsigns:
      description: Allows a player to see sign placements as chat messages.
      default: op
    restorenatureaggressive:
      description: Grants access to /RestoreNatureAggressive and /RestoreNatureFill.
      default: op
    deathblow:
      description: Grants access to /DeathBlow.
      default: op
    reload:
      description: Grants access to /gpreload.
      default: op
    softmute:
      description: Grants access to /SoftMute.
      default: op
    claims:
      description: Grants access to claim-related slash commands.
      default: true
    buysellclaimblocks:
      description: Grants access to claim block buy/sell commands.
      default: true
    visualizenearbyclaims:
      description: Allows a player to see all nearby claims at once.
      default: op
    seeclaimsize:
      description: Allows a player to see claim size for other players claims when
        right clicking with investigation tool
      default: op
    gpblockinfo:
      description: Grants access to /GPBlockInfo.
      default: op
    overrideclaimcountlimit:
      description: Allows players to create more claims than the limit specified by
        the config.
      default: op
    separate:
      description: Grants access to /Separate and /UnSeparate.
      default: op
    ignore:
      description: Grants access to /Ignore, /Unignore, and /IgnoreList
      default: true
    claimbook:
      description: Grants access to /ClaimBook.
      default: op
    notignorable:
      description: Players with this permission can't be ignored.
      default: op
    seeinactivity:
      description: Players with this permission can see how long a claim owner has
        been offline.
      default: op
    eavesdropimmune:
      description: Players with this permission can't have their private messages
        eavesdropped.
      default: op
    fasteraccrual:
      description: Players with this permission accrue claim blocks at the faster
        rate specified in the config file.
      default: false
    fastestaccrual:
      description: Players with this permission accrue claim blocks at the fastest
        rate specified in the config file.
      default: false
    moreaccrued:
      description: Players with this permission can accrue more claim blocks (limit
        specified in the config file).
      default: false
    mostaccrued:
      description: Players with this permission can accrue more claim blocks (limit
        specified in the config file).
      default: false
    siegeteleport:
      description: Players with this permission can teleport into and out of besieged
        areas.
      default: op
